### ISSUE TITLE
Instantiable while building error

### ISSUE THREAD

**Issue by pitchayakit** [wdelfuego/nova-calendar#17]
I tried to follow the document and got this error.
Could you please address this issue?

Nova v4.9.2
Laravel Framework 9.17.0
![image](https://user-images.githubusercontent.com/17026022/174306575-d1087b55-25f3-4abb-a874-db8434a5a51c.png)

**Comment by wdelfuego** [comment]
Hi! This could happen if you don’t properly bind the CalendarDataProvider to the interface in the ‘register’ method of your NovaServiceProvider. 

Could you copy paste that method here so I can check if it’s correct? Also make sure you’ve put the proper use statements at the beginning of that file so it references the properly namespaces ‘CalendarDataProviderInterface’.

**Comment by pitchayakit** [comment]
Hi
Thanks for your quick reply.

Actually, I used default calendar data provider which came from 
`php artisan nova-calendar:create-default-calendar-data-provider `
I didn't touch anything with that data provider as well.

![image](https://user-images.githubusercontent.com/17026022/174328245-ed3d9de9-b00a-4e52-9e3f-995cc5a9a4f6.png)

**Comment by wdelfuego** [comment]
Can you post the entire contents of your NovaServiceProvider.php file?

**Comment by pitchayakit** [comment]
Hi
This is my NovaServiceProvider.php
```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Gate;
use Laravel\Nova\Nova;
use Laravel\Nova\NovaApplicationServiceProvider;
use Illuminate\Support\Facades\Auth;
use App\Nova\Dashboards\Main;
use Wdelfuego\NovaCalendar\NovaCalendar;
use Wdelfuego\NovaCalendar\Contracts\CalendarDataProviderInterface;
use App\Providers\CalendarDataProvider;

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();
    }

    /**
     * Register the Nova routes.
     *
     * @return void
     */
    protected function routes()
    {
        Nova::routes()
                ->withAuthenticationRoutes()
                ->withPasswordResetRoutes()
                ->register();
    }

    /**
     * Register the Nova gate.
     *
     * This gate determines who can access Nova in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewNova', function ($user) {
            return Auth::check();
        });
    }

    /**
     * Get the cards that should be displayed on the default Nova dashboard.
     *
     * @return array
     */
    protected function cards()
    {
        return [
            //new Help,
        ];
    }

    /**
     * Get the extra dashboards that should be displayed on the Nova dashboard.
     *
     * @return array
     */
    protected function dashboards()
    {
        return [
            new Main,
        ];
    }

    /**
     * Get the tools that should be listed in the Nova sidebar.
     *
     * @return array
     */
    public function tools()
    {
        return [
            new \Pktharindu\NovaPermissions\NovaPermissions(),
            new NovaCalendar()
        ];
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(CalendarDataProviderInterface::class, function($app) {
            return new CalendarDataProvider();
        });
    }
}
```

**Comment by wdelfuego** [comment]
I see. There is an error in the readme that I will fix asap. 

In your NovaServiceProvider, replace this line:

    use Wdelfuego\NovaCalendar\Contracts\CalendarDataProviderInterface;

with this:
    use Wdelfuego\NovaCalendar\Interface\CalendarDataProviderInterface;
    
I think that should fix your error. 
Please let me know!

**Comment by pitchayakit** [comment]
Yes, It works. Thanks your help :)

**Comment by wdelfuego** [comment]
Fixed the mistake in the Readme. Thank _you_ for reporting or it would've been there for longer :)!
