### ISSUE TITLE
Calendar menu link giving 404

### ISSUE THREAD

**Issue by alexWaterfront** [wdelfuego/nova-calendar#23]
I am using the latest nova version and just installed nova-calendar. I have removed the nova prefix from my url through the config file of nova and its just '/' . When i add the calendar in the menu the modal shows 404 no page found. Any help with this is much appreciated

**Comment by wdelfuego** [comment]
Hey Alex, were you able to solve the issue? :)

**Comment by alexWaterfront** [comment]
Hi @wdelfuego yes i did, just had to run composer dump-autoload, stupid from my side sorry for polluting your repo :)

**Comment by wdelfuego** [comment]
No worries, might happen to others too so it's good to have it documented 👍 . Glad you got it to work!
