### ISSUE TITLE
Consider PHP8.0

### ISSUE THREAD

**Issue by alekmlynek** [wdelfuego/nova-calendar#37]
This package will not install on my version of PHP, which is 8.0.24. I would suggest considering making it PHP 8.0 compatible. For now, all AWS PHP-managed instances are using 8.0.*, and so many of us that deploy to Amazon are locked into it. Otherwise, the package looks really promising.

**Comment by wdelfuego** [comment]
The project was already 8.0 compatible, it was just untested so the composer.json was overly restrictive.
I've just confirmed that it works and released 1.6.1 that does allow you to install on php 8.0.

Let me know if you run into any issues with this package, php related or not :).

Thanks for creating this issue!
