### ISSUE TITLE
Event filtering

### ISSUE THREAD

**Issue by henryavila** [wdelfuego/nova-calendar#45]
Hi, first of all, this package is amazing. Thanks for sharing it, and sorry about  the title. I couln't define one with short words.

The only feature that I miss is the ability to filters events from an specific calendar. I will try to explain:

The idea is to keep just one instance of the Tool in nova.
Imagine that whe have 2 calendars in DB, and for each calendar, we have multiple events:

```
Calendar 1: Family
---- Event 1
---- Event 2
---- Event 3

Calendar 2: Job
---- Event 10
---- Event 11
---- Event 12
---- Event 13
```

The Idea is be able to display teh events of just one of this calendars per time, and be able to change the calendar that is been displayed.

**Comment by wdelfuego** [comment]
This feature will be released as part of the 2.x branch, probably around the end of February, possibly as part of the 2.0 release :)!

**Comment by wdelfuego** [comment]
(This will be implemented as event filtering, so you will make 1 CalendarDataProvider that contains events of both calendars, then create filters to let the user choose between different subsets of the events on the calendar).

**Comment by henryavila** [comment]
Awsome @wdelfuego.
In my case, the filter will be the Event parent model. 

Thanks for the reply.

**Comment by wdelfuego** [comment]
Event filtering has been launched today as part of the 2.0 release.

You can find the Upgrade guide to 2.0 here: https://wdelfuego.github.io/nova-calendar/upgrading.html
You can find documentation on the filtering feature here: https://wdelfuego.github.io/nova-calendar/event-filters.html

Please, create issues for any doubts you may have or issues you may run into 🙏.
