### ISSUE TITLE
Allow us to include html inside the event notes

### ISSUE THREAD

**Issue by vesper8** [wdelfuego/nova-calendar#47]
I tried adding some simple html inside my notes so that I could style part of the note differently and the html itself got printed as a string. This may require letting us use the `v-html` directive which in some cases can be unsafe but as part of an internal admin tool I think it would be fine.

I have emojis as part of my notes and they are really tiny right now and I would like them to stand out more, but don't want to make all the text bigger.

And I'm also already using badges, but I need to use both badges and emojis inside the notes.

Let me know if that's that possible :)

Thanks!

**Comment by wdelfuego** [comment]
Merged and released in v1.7
