### ISSUE TITLE
Customizing Event properties in custom event generator

### ISSUE THREAD

**Issue by Sonicelo** [wdelfuego/nova-calendar#50]
Thank you for creating and sharing this package;
I am trying to implement reoccurring events (currently simply Users birthday, later reoccurring tasks). I got the query working well but my issue is the event creation process, as I need to modify the original year, to the one currently being displayed (which can be for current month either last year or current year even).

Would it be possible to gain access to the `$startOfCalendar` and `$endOfCalendar` within the `resourceToEvents` function or am I missing something?

Or maybe even as callable function or property of the `EventGenerator` class?

**Comment by wdelfuego** [comment]
If you want to modify the year of events generated by a custom event generator, you could always do so in your CalendarDataProvider's `customizeEvent` method.

If you prefer your custom event generator to generate events that already have a modified year, you could override its `generateEvents` method, which gets `$rangeStart` and `$rangeEnd` arguments, like this;

```
use Wdelfuego\NovaCalendar\EventGenerator\Custom as CustomEventGenerator;
use Wdelfuego\NovaCalendar\Event;

class MyCustomEventGenerator extends CustomEventGenerator
{
    // Implement modelQuery and resourceToEvents methods

    public function generateEvents(Carbon $rangeStart, Carbon $rangeEnd) : array
    {
        $out = parent::generateEvents($rangeStart, $rangeEnd)
        // Loop over $out to modify events
        return $out;
    }
}
```

Let me know if this is helpful :)!

**Comment by wdelfuego** [comment]
`$rangeStart` and `$rangeEnd` will be available in the `resourceToEvents` method as of v2 of this package. Marking this issue as resolved for now.
