### ISSUE TITLE
   ERROR  There are no commands defined in the "nova-calendar" namespace.  

### ISSUE THREAD

**Issue by BeiAduo** [wdelfuego/nova-calendar#57]
php artisan nova-calendar:create-default-calendar-data-provider
   ERROR  There are no commands defined in the "nova-calendar" namespace.

**Comment by wdelfuego** [comment]
I can't reproduce this error, are you sure the package is correctly installed in your project?

To check, what is the output of running `composer show wdelfuego/nova-calendar` in your project directory?

**Comment by wdelfuego** [comment]
Can't reproduce; closing due to lack of info
