### ISSUE TITLE
Week View Update?

### ISSUE THREAD

**Issue by jeremiahsherrill** [wdelfuego/nova-calendar#63]
Did you roll back todays changes, I got this notice

added week view to Nova Calendar
views can be enabled in nova-calendar.php config file, selector buttons are located in top right area
direct links from month view to selected week enabled
README updated

**Comment by wdelfuego** [comment]
The pull request for those features was created yesterday by @bb140856. The pull request is currently in review, we're finalizing the Week view for release. Nothing was merged or rolled back yet.
