### ISSUE TITLE
month and year pickers disappear on press

### ISSUE THREAD

**Issue by Eli-Pez** [wdelfuego/nova-calendar#69]
The new month/year picker of version 2.1 (https://github.com/wdelfuego/nova-calendar#v21) does not work well. When i try to select something, it disappears and does not leave time to select anything.

https://github.com/wdelfuego/nova-calendar/assets/145749363/828a2591-0ebf-4313-ad85-b3c2e79c7552

**Comment by wdelfuego** [comment]
Thanks for reporting and including the clear video!

A couple of questions;
- Which version of macOS are you using?
- Which browser and which version of it are you using?
- Which version of Nova are you using?
- Do you see any output in the console that indicates a problem when using the picker?

**Comment by Eli-Pez** [comment]
- MacOs version: 13.5.2
- I'm on Chrome 117.0.5938.88. It works on Safari! Stupid me that i haven't tried before.
- Nova 4.27.13
- in console there are no errors or warnings

Furthermore i can see there is no dark mode style for the two dropdowns in both browsers.

**Comment by wdelfuego** [comment]
Thanks for the info! There was indeed a bug going on in Chrome.

Fixed in v2.1.1, added dark mode support to the select dropdowns, too.

Thanks for reporting!
