### ISSUE TITLE
BindingResolutionException: Target class [] does not exist. when caching routes

### ISSUE THREAD

**Issue by Hannoma** [wdelfuego/nova-calendar#71]
Please find the full log here: https://flareapp.io/share/Lm89jgpP
This error only happens when the routes are cached.

**Comment by wdelfuego** [comment]
@Hannoma was that helpful? Are you still running into this?

**Comment by wdelfuego** [comment]
@Hannoma Any update?

**Comment by Hannoma** [comment]
Figured it out. The problem is https://github.com/Formfeed-UK/nova-breadcrumbs as this package uses the `getController` function as well. Opened an issue and PR over there https://github.com/Formfeed-UK/nova-breadcrumbs/pull/39
