### ISSUE TITLE
It is possible to change the URL by clicking the event to access a custom tool instead of using the resource?

### ISSUE THREAD

**Issue by HAL0594** [wdelfuego/nova-calendar#73]
I'm using 2.x and I have a calenda

By default, clicking takes you to the resource event view

`/nova/resource/resourceName/{id}`

which I am only using to get the calendar events but it should take me to the tool view

`/nova/mytool/mytoolview/{param1}/{param2}`

Is there a way to do it or to obtain the events directly from the model, omitting the resource and the click?

**Comment by wdelfuego** [comment]
Take a look at the url and withUrl methods mentioned at https://wdelfuego.github.io/nova-calendar/customizing-events.html#chainable-customization-methods

**Comment by wdelfuego** [comment]
And, more importantly;

https://wdelfuego.github.io/nova-calendar/customizing-events.html#changing-what-happens-when-an-event-is-clicked
