### ISSUE TITLE
Vue warning DropdownTrigger

### ISSUE THREAD

**Issue by Nikolai-Kaskatiiski** [wdelfuego/nova-calendar#79]
Hi, I have those warnings 
[Vue warn]: Failed to resolve component: DropdownTrigger
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
I have being playing with component long time, just notice them right now.
I am with nova 4.32.11 it it matters.
Please help

**Comment by wdelfuego** [comment]
Mhm, I'm having a hard time reproducing this; could you produce a repo with a clean install of Nova + nova-calendar that presents this issue?

**Comment by Nikolai-Kaskatiiski** [comment]
Hi, thank you for the prompt replay. I will do it ASAP

**Comment by wdelfuego** [comment]
Hi @Nikolai-Kaskatiiski, did you get a chance to reproduce the issue in a clean repo?

**Comment by wdelfuego** [comment]
Closing due to lack of reproducibility. 

Feel free to update this issue if you can reproduce the issue in a clean repo and I'll look into it.
